# Generated by Django 5.1.2 on 2024-10-30 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_pelicula_imagen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='visualizacion',
            old_name='fecha',
            new_name='fecha_visualizacion',
        ),
        migrations.AlterUniqueTogether(
            name='visualizacion',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='visualizacion',
            name='pelicula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizaciones_usuario', to='users.pelicula'),
        ),
        migrations.AlterField(
            model_name='visualizacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
